# Use a minimal Node.js image
FROM node:alpine

# Set the working directory
WORKDIR /app

# Copy the JavaScript file
COPY src/ .

# Expose port if needed
EXPOSE 8080

# Command to run the JavaScript file
CMD ["node", "index.js"]
